import { HustleDefinition, HustleId, ModifierDefinition } from '../game-engine/types';
import {
  GRIFT_OS_HUSTLE_TUNING,
  GRIFT_OS_MILESTONE_TUNING,
} from './economy-tuning';

function milestoneReward(
  hustleId: HustleId,
  milestone: (typeof GRIFT_OS_MILESTONE_TUNING)[HustleId][number]
): ModifierDefinition {
  return {
    id: `${hustleId}-units-${milestone.requiredUnits}-${milestone.kind}`,
    label: milestone.label,
    description: milestone.rewardDescription,
    scope: 'hustle',
    kind: milestone.kind,
    value: milestone.value,
    hustleId,
    source: 'milestone',
  };
}

function milestoneSet(
  hustleId: HustleId,
  unitPlural: string
): HustleDefinition['milestones'] {
  return GRIFT_OS_MILESTONE_TUNING[hustleId].map((milestone) => ({
    id: `${hustleId}-${milestone.requiredUnits}`,
    requiredUnits: milestone.requiredUnits,
    name: `${milestone.requiredUnits} ${unitPlural}`,
    description: milestone.description,
    reward: milestoneReward(hustleId, milestone),
  }));
}

export const HUSTLE_DEFINITIONS: readonly HustleDefinition[] = [
  {
    id: 'troll-network',
    ...GRIFT_OS_HUSTLE_TUNING['troll-network'],
    name: 'Creator Account',
    description: 'Turn borrowed reach into microscopic transactions one link at a time.',
    unitSingular: 'Account',
    unitPlural: 'Accounts',
    expansionActionLabel: 'Add Account',
    manualActionLabel: 'Post an Affiliate Link',
    automationName: 'Link-in-Bio Router',
    automationDescription: 'Keep offers rotating while the Founder is busy manufacturing relevance.',
    order: 1,
    iconKind: 'signal',
    milestones: milestoneSet('troll-network', 'Accounts'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'creator-scroll',
    },
  },
  {
    id: 'podcast-network',
    ...GRIFT_OS_HUSTLE_TUNING['podcast-network'],
    name: 'Subscriber Club',
    description: 'Charge the most committed followers for recurring access and belonging.',
    unitSingular: 'Tier',
    unitPlural: 'Tiers',
    expansionActionLabel: 'Add Tier',
    manualActionLabel: 'Sell a Subscription',
    automationName: 'Membership Platform',
    automationDescription: 'Handle renewals, gated feeds, and status without personal attention.',
    order: 2,
    iconKind: 'broadcast',
    milestones: milestoneSet('podcast-network', 'Tiers'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'member-chime',
    },
  },
  {
    id: 'culture-war-media',
    ...GRIFT_OS_HUSTLE_TUNING['culture-war-media'],
    name: 'Merch Operation',
    description: 'Sell visible proof that the audience belongs to the audience.',
    unitSingular: 'Drop',
    unitPlural: 'Drops',
    expansionActionLabel: 'Add Drop',
    manualActionLabel: 'Launch a Merch Drop',
    automationName: 'Fulfillment Partner',
    automationDescription: 'Move limited editions without the Founder touching a shipping label.',
    order: 3,
    iconKind: 'outrage',
    milestones: milestoneSet('culture-war-media', 'Drops'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'fulfillment-line',
    },
  },
  {
    id: 'masterclass-business',
    ...GRIFT_OS_HUSTLE_TUNING['masterclass-business'],
    name: 'Personality Show',
    description: 'Package recurring attention into sponsor-ready inventory.',
    unitSingular: 'Show',
    unitPlural: 'Shows',
    expansionActionLabel: 'Add Show',
    manualActionLabel: 'Sell a Sponsor Read',
    automationName: 'Ad Sales Desk',
    automationDescription: 'Keep endorsements booked across every episode and feed.',
    order: 4,
    iconKind: 'funnel',
    milestones: milestoneSet('masterclass-business', 'Shows'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'studio-clock',
    },
  },
  {
    id: 'manifesto-imprint',
    ...GRIFT_OS_HUSTLE_TUNING['manifesto-imprint'],
    name: 'Appearance Circuit',
    description: 'Convert online recognition into tickets, photos, and premium proximity.',
    unitSingular: 'Date',
    unitPlural: 'Dates',
    expansionActionLabel: 'Add Date',
    manualActionLabel: 'Sell VIP Access',
    automationName: 'Booking Agency',
    automationDescription: 'Keep venues, upgrades, and paid appearances moving city to city.',
    order: 5,
    iconKind: 'manifesto',
    milestones: milestoneSet('manifesto-imprint', 'Dates'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'venue-crowd',
    },
  },
  {
    id: 'founder-retreat-circuit',
    ...GRIFT_OS_HUSTLE_TUNING['founder-retreat-circuit'],
    name: 'Inner Circle',
    description: 'Turn belonging into ranked access, advancement fees, and escalating dues.',
    unitSingular: 'Chapter',
    unitPlural: 'Chapters',
    expansionActionLabel: 'Add Chapter',
    manualActionLabel: 'Advance a Member',
    automationName: 'Advancement Council',
    automationDescription: 'Administer rank, dues, and loyalty without interrupting the mystique.',
    order: 6,
    iconKind: 'summit',
    milestones: milestoneSet('founder-retreat-circuit', 'Chapters'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'inner-circle',
    },
  },
  {
    id: 'ai-venture',
    ...GRIFT_OS_HUSTLE_TUNING['ai-venture'],
    name: 'Fundraising Machine',
    description: 'Convert every crisis, attack, and ordinary expense into recurring urgency.',
    unitSingular: 'Campaign',
    unitPlural: 'Campaigns',
    expansionActionLabel: 'Add Campaign',
    manualActionLabel: 'Declare an Emergency',
    automationName: 'Crisis Calendar',
    automationDescription: 'Keep the next existential deadline ready before the current one expires.',
    order: 7,
    iconKind: 'ai',
    milestones: milestoneSet('ai-venture', 'Campaigns'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'donation-counter',
    },
  },
  {
    id: 'venture-portfolio',
    ...GRIFT_OS_HUSTLE_TUNING['venture-portfolio'],
    name: 'Community Coin',
    description: 'Turn parasocial conviction into presales, allocations, and replacement tokens.',
    unitSingular: 'Issue',
    unitPlural: 'Issues',
    expansionActionLabel: 'Add Issue',
    manualActionLabel: 'Open a Presale',
    automationName: 'Token Operations Desk',
    automationDescription: 'Coordinate allocations, liquidity, and the next improved community asset.',
    order: 8,
    iconKind: 'fund',
    milestones: milestoneSet('venture-portfolio', 'Issues'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'token-ticks',
    },
  },
  {
    id: 'media-holdings',
    ...GRIFT_OS_HUSTLE_TUNING['media-holdings'],
    name: 'Personality Network',
    description: 'Own other personalities, combine their audiences, and sell at network scale.',
    unitSingular: 'Personality',
    unitPlural: 'Personalities',
    expansionActionLabel: 'Sign Personality',
    manualActionLabel: 'Sell a Network Campaign',
    automationName: 'Brand Partnerships Office',
    automationDescription: 'Package talent and audience inventory into campaigns too large to ignore.',
    order: 9,
    iconKind: 'media',
    milestones: milestoneSet('media-holdings', 'Personalities'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'network-bed',
    },
  },
  {
    id: 'sovereign-network',
    ...GRIFT_OS_HUSTLE_TUNING['sovereign-network'],
    name: 'Social Platform',
    description: 'Own the market where everyone else converts attention into money.',
    unitSingular: 'Ad Market',
    unitPlural: 'Ad Markets',
    expansionActionLabel: 'Add Ad Market',
    manualActionLabel: 'Auction Ad Inventory',
    automationName: 'Programmatic Exchange',
    automationDescription: 'Price and sell attention continuously across the entire platform.',
    order: 10,
    iconKind: 'sovereignty',
    milestones: milestoneSet('sovereign-network', 'Ad Markets'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'platform-exchange',
    },
  },
];
