import { HustleDefinition, HustleId, ModifierDefinition } from '../game-engine/types';

function outputMilestone(
  hustleId: HustleId,
  requiredUnits: number,
  bonus: number,
  name: string,
  description: string
): ModifierDefinition {
  return {
    id: `${hustleId}-units-${requiredUnits}-output`,
    label: `+${Math.round(bonus * 100)}% local output`,
    description,
    scope: 'hustle',
    kind: 'output',
    value: bonus,
    hustleId,
    source: 'milestone',
  };
}

function milestoneSet(
  hustleId: HustleId,
  unitPlural: string
): HustleDefinition['milestones'] {
  const milestones = [
    {
      requiredUnits: 10,
      bonus: 0.5,
      description: 'The Hustle stops looking accidental.',
      rewardDescription: 'First visible scale effect.',
    },
    {
      requiredUnits: 25,
      bonus: 1,
      description: 'The machine becomes easier to mistake for inevitability.',
      rewardDescription: 'Local output doubles from repeated expansion.',
    },
    {
      requiredUnits: 50,
      bonus: 0.75,
      description: 'The operation starts producing its own internal folklore.',
      rewardDescription: 'The Hustle compounds from accumulated surface area.',
    },
    {
      requiredUnits: 100,
      bonus: 1,
      description: 'The audience begins treating repetition as validation.',
      rewardDescription: 'Local output gains another mature-scale lift.',
    },
    {
      requiredUnits: 250,
      bonus: 1.25,
      description: 'The Hustle becomes too large to read as a side quest.',
      rewardDescription: 'Institutional scale improves local output.',
    },
    {
      requiredUnits: 500,
      bonus: 1.5,
      description: 'The machine starts defending itself from boredom.',
      rewardDescription: 'Portfolio-scale density boosts local output.',
    },
    {
      requiredUnits: 1000,
      bonus: 2,
      description: 'The Hustle is now part of the landscape it claims to disrupt.',
      rewardDescription: 'Dominant scale creates the largest current local-output lift.',
    },
  ] as const;

  return milestones.map((milestone) => ({
    id: `${hustleId}-${milestone.requiredUnits}`,
    requiredUnits: milestone.requiredUnits,
    name: `${milestone.requiredUnits} ${unitPlural}`,
    description: milestone.description,
    reward: outputMilestone(
      hustleId,
      milestone.requiredUnits,
      milestone.bonus,
      `${milestone.requiredUnits} ${unitPlural}`,
      milestone.rewardDescription
    ),
  }));
}

export const HUSTLE_DEFINITIONS: readonly HustleDefinition[] = [
  {
    id: 'troll-network',
    name: 'Troll Network',
    description: 'Convert replies into proof that the market is listening.',
    unitSingular: 'Forum',
    unitPlural: 'Forums',
    expansionActionLabel: 'Add Forum',
    manualActionLabel: 'Troll People Online',
    automationName: 'Bots',
    automationDescription: 'Scale authentic disagreement without the authenticity bottleneck.',
    automationCost: 110,
    acquisitionCost: 50,
    growthRate: 1.138,
    basePayout: 4,
    cadenceSeconds: 2,
    initialUnits: 1,
    order: 1,
    iconKind: 'signal',
    milestones: milestoneSet('troll-network', 'Forums'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'network-noise',
    },
  },
  {
    id: 'podcast-network',
    name: 'Podcast Network',
    description: 'Convert microphone ownership into civilizational authority.',
    unitSingular: 'Show',
    unitPlural: 'Shows',
    expansionActionLabel: 'Launch Show',
    manualActionLabel: 'Record an Episode',
    automationName: 'Clip Farm',
    automationDescription: 'Atomize long-form certainty into algorithm-compatible conviction.',
    automationCost: 750,
    acquisitionCost: 160,
    growthRate: 1.15,
    basePayout: 28,
    cadenceSeconds: 5,
    initialUnits: 0,
    order: 2,
    iconKind: 'broadcast',
    milestones: milestoneSet('podcast-network', 'Shows'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'broadcast-loop',
    },
  },
  {
    id: 'culture-war-media',
    name: 'Culture-War Media',
    description: 'Transform ambient insecurity into recurring engagement.',
    unitSingular: 'Channel',
    unitPlural: 'Channels',
    expansionActionLabel: 'Add Channel',
    manualActionLabel: 'Pick a Fight',
    automationName: 'Outrage Engine',
    automationDescription: 'Schedule grievance so the machine never has to sleep.',
    automationCost: 5200,
    acquisitionCost: 900,
    growthRate: 1.16,
    basePayout: 150,
    cadenceSeconds: 9,
    initialUnits: 0,
    order: 3,
    iconKind: 'outrage',
    milestones: milestoneSet('culture-war-media', 'Channels'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'outrage-pulse',
    },
  },
  {
    id: 'masterclass-business',
    name: 'Masterclass Business',
    description: 'Monetize the discovery that your own success happened.',
    unitSingular: 'Course',
    unitPlural: 'Courses',
    expansionActionLabel: 'Add Course',
    manualActionLabel: 'Sell a Masterclass',
    automationName: 'Funnel Stack',
    automationDescription: 'Convert curiosity into checkout-page inevitability.',
    automationCost: 44000,
    acquisitionCost: 6500,
    growthRate: 1.15,
    basePayout: 950,
    cadenceSeconds: 15,
    initialUnits: 0,
    order: 4,
    iconKind: 'funnel',
    milestones: milestoneSet('masterclass-business', 'Courses'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'checkout-hum',
    },
  },
  {
    id: 'manifesto-imprint',
    name: 'Manifesto Imprint',
    description: 'Convert opinions into a theory of history.',
    unitSingular: 'Title',
    unitPlural: 'Titles',
    expansionActionLabel: 'Commission Title',
    manualActionLabel: 'Publish a Manifesto',
    automationName: 'Ghostwriting Collective',
    automationDescription: 'Scale revelation without waiting for coherence.',
    automationCost: 360000,
    acquisitionCost: 50000,
    growthRate: 1.145,
    basePayout: 7200,
    cadenceSeconds: 24,
    initialUnits: 0,
    order: 5,
    iconKind: 'manifesto',
    milestones: milestoneSet('manifesto-imprint', 'Titles'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'manifesto-drone',
    },
  },
  {
    id: 'founder-retreat-circuit',
    name: 'Founder Retreat Circuit',
    description: 'Put rich people in a room until networking becomes destiny.',
    unitSingular: 'City',
    unitPlural: 'Cities',
    expansionActionLabel: 'Add City',
    manualActionLabel: 'Host a Retreat',
    automationName: 'Social Graph Concierge',
    automationDescription: 'Optimize proximity until everyone mistakes it for strategy.',
    automationCost: 3000000,
    acquisitionCost: 420000,
    growthRate: 1.14,
    basePayout: 54000,
    cadenceSeconds: 38,
    initialUnits: 0,
    order: 6,
    iconKind: 'summit',
    milestones: milestoneSet('founder-retreat-circuit', 'Cities'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'salon-loop',
    },
  },
  {
    id: 'ai-venture',
    name: 'AI Venture',
    description: 'Reclassify roadmap uncertainty as emergent intelligence.',
    unitSingular: 'Product Line',
    unitPlural: 'Product Lines',
    expansionActionLabel: 'Launch Product Line',
    manualActionLabel: 'Demo the Future',
    automationName: 'Synthetic Demo Team',
    automationDescription: 'Ensure the future appears functional in controlled lighting.',
    automationCost: 25000000,
    acquisitionCost: 3500000,
    growthRate: 1.135,
    basePayout: 360000,
    cadenceSeconds: 60,
    initialUnits: 0,
    order: 7,
    iconKind: 'ai',
    milestones: milestoneSet('ai-venture', 'Product Lines'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'demo-bloom',
    },
  },
  {
    id: 'venture-portfolio',
    name: 'Venture Portfolio',
    description: 'Turn prior access into evidence of future insight.',
    unitSingular: 'Portfolio Company',
    unitPlural: 'Portfolio Companies',
    expansionActionLabel: 'Back Company',
    manualActionLabel: 'Place a Bet',
    automationName: 'Associate Swarm',
    automationDescription: 'Convert other people\'s pattern matching into deal flow.',
    automationCost: 210000000,
    acquisitionCost: 30000000,
    growthRate: 1.13,
    basePayout: 2500000,
    cadenceSeconds: 95,
    initialUnits: 0,
    order: 8,
    iconKind: 'fund',
    milestones: milestoneSet('venture-portfolio', 'Portfolio Companies'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'capital-cycle',
    },
  },
  {
    id: 'media-holdings',
    name: 'Media Holdings',
    description: 'Increase the market\'s freedom to encounter your worldview.',
    unitSingular: 'Outlet',
    unitPlural: 'Outlets',
    expansionActionLabel: 'Acquire Outlet',
    manualActionLabel: 'Acquire an Outlet',
    automationName: 'Editorial Independence',
    automationDescription: 'Let the publication organically discover your priors.',
    automationCost: 1800000000,
    acquisitionCost: 260000000,
    growthRate: 1.125,
    basePayout: 18000000,
    cadenceSeconds: 150,
    initialUnits: 0,
    order: 9,
    iconKind: 'media',
    milestones: milestoneSet('media-holdings', 'Outlets'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'media-bed',
    },
  },
  {
    id: 'sovereign-network',
    name: 'Sovereign Network',
    description: 'Exit the legacy state without leaving the investor group chat.',
    unitSingular: 'Jurisdiction',
    unitPlural: 'Jurisdictions',
    expansionActionLabel: 'Add Jurisdiction',
    manualActionLabel: 'Expand the Stack',
    automationName: 'Aligned Population',
    automationDescription: 'Resolve governance by ensuring the users are already selected.',
    automationCost: 15000000000,
    acquisitionCost: 2200000000,
    growthRate: 1.12,
    basePayout: 140000000,
    cadenceSeconds: 240,
    initialUnits: 0,
    order: 10,
    iconKind: 'sovereignty',
    milestones: milestoneSet('sovereign-network', 'Jurisdictions'),
    audio: {
      manualActionCue: 'manual-click',
      automationCue: 'automation-online',
      ambientSignature: 'sovereign-grid',
    },
  },
];
